# Generated by Django 6.0 on 2025-12-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=100, unique=True)),
                ('office_full_name', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('established', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Office',
                'verbose_name_plural': 'Offices',
                'ordering': ['-created_at'],
            },
        ),
    ]
