# Generated by Django 6.0 on 2025-12-22 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('eng_name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9, unique=True)),
                ('eng_name', models.CharField(blank=True, max_length=20, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('start_year', models.IntegerField(blank=True, null=True, unique=True)),
                ('end_year', models.IntegerField(blank=True, null=True, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Office_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(max_length=200)),
                ('established_date', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('nishan_chap', models.ImageField(blank=True, null=True, upload_to='images/nishan_chap/')),
                ('office_logo', models.ImageField(blank=True, null=True, upload_to='images/office_logo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='दर्ता नम्बर')),
                ('plan_name', models.TextField(verbose_name='आयोजनाको नाम')),
                ('ward_number', models.CharField(max_length=10, verbose_name='वडा नं.')),
                ('location', models.TextField(verbose_name='स्थान')),
                ('allocated_budget', models.BigIntegerField(verbose_name='विनियोजित बजेट')),
                ('implementation_level', models.CharField(max_length=50, verbose_name='कार्यान्वयन तह')),
                ('implementation_status', models.CharField(max_length=50, verbose_name='कार्यान्वयनको अवस्था')),
                ('date', models.CharField(max_length=20, verbose_name='मिति')),
            ],
            options={
                'ordering': ['registration_number'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, unique=True)),
                ('ward_location', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('register_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_date', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committee_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.committeetype')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ward')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('father_name', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('citizenship_number', models.CharField(help_text='Unique citizenship number to prevent duplicate members', max_length=100, unique=True)),
                ('sex', models.CharField(choices=[('male', 'पुरुष'), ('female', 'महिला')], default='male', max_length=10)),
                ('designation', models.CharField(choices=[('adhyaksha', 'अध्यक्ष'), ('upadhyaksha', 'उपाध्यक्ष'), ('sachiv', 'सचिव'), ('kosadhyaksha', 'कोषाध्यक्ष'), ('sadasya', 'सदस्य')], default='sadasya', max_length=50)),
                ('is_account_holder', models.BooleanField(default=False, help_text='Is this member an account holder?')),
                ('is_monitoring_committee_member', models.BooleanField(default=False, help_text='Is this member in monitoring committee?')),
                ('role_priority', models.PositiveIntegerField(default=99)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.committee')),
            ],
            options={
                'ordering': ['role_priority', 'name'],
            },
        ),
    ]
