# Generated by Django 6.0.1 on 2026-01-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='दर्ता नम्बर')),
                ('plan_name', models.TextField(verbose_name='आयोजनाको नाम')),
                ('ward_number', models.CharField(max_length=10, verbose_name='वडा नं.')),
                ('location', models.TextField(verbose_name='स्थान')),
                ('allocated_budget', models.BigIntegerField(verbose_name='विनियोजित बजेट')),
                ('implementation_level', models.CharField(max_length=50, verbose_name='कार्यान्वयन तह')),
                ('implementation_status', models.CharField(max_length=50, verbose_name='कार्यान्वयनको अवस्था')),
                ('date', models.CharField(max_length=20, verbose_name='मिति')),
            ],
            options={
                'ordering': ['registration_number'],
            },
        ),
    ]
