# Generated by Django 6.0 on 2025-12-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_eng', models.CharField(max_length=100, unique=True)),
                ('committee_type_code', models.CharField(default='CT001', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Committee Type',
                'verbose_name_plural': 'Committee Types',
                'ordering': ['-created_at'],
            },
        ),
    ]
