# Generated by Django 6.0 on 2025-12-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_office_model_delete_committeetype_delete_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='office_model',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='office_model',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='office_model',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
