# Generated by Django 6.0 on 2025-12-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='ward_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
