# Generated by Django 6.0 on 2025-12-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_committee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Committee',
        ),
    ]
