# Generated by Django 6.0 on 2025-12-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
