# Generated by Django 6.0 on 2025-12-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_eng', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
