# Generated by Django 6.0 on 2025-12-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_committeetype_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiscalyear',
            old_name='fiscalyear',
            new_name='name',
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='end_year',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='eng_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='start_year',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
