# Generated by Django 6.0 on 2025-12-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_fiscalyear_fiscalyear_name_fiscalyear_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committeetype',
            old_name='name_eng',
            new_name='eng_name',
        ),
    ]
