# Generated by Django 6.0 on 2025-12-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_name_eng_committeetype_eng_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='created_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
