# Generated by Django 6.0 on 2025-12-12 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_committee_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('father_name', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('citizenship_number', models.CharField(help_text='Unique citizenship number to prevent duplicate members', max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('sex', models.CharField(choices=[('male', 'पुरुष'), ('female', 'महिला')], default='male', max_length=10)),
                ('role', models.CharField(choices=[('adhyaksha', 'अध्यक्ष'), ('upadhyaksha', 'उपाध्यक्ष'), ('sachiv', 'सचिव'), ('kosadhyaksha', 'कोषाध्यक्ष'), ('sadasya', 'सदस्य'), ('anugaman', 'अनुगमन समिति')], default='sadasya', max_length=50)),
                ('is_account_holder', models.BooleanField(default=False, help_text='Is this member an account holder?')),
                ('role_priority', models.PositiveIntegerField(default=99)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.committee')),
            ],
            options={
                'ordering': ['role_priority', 'name'],
            },
        ),
    ]
