# Generated by Django 6.0 on 2025-12-12 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committee',
            options={},
        ),
    ]
