# Generated by Django 6.0 on 2025-12-12 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_committee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committee',
            options={'ordering': ['-created_at']},
        ),
    ]
