# Generated by Django 6.0 on 2025-12-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_committee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_monitoring_committee',
            field=models.BooleanField(default=False, help_text='Is this member in monitoring committee?'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('adhyaksha', 'अध्यक्ष'), ('upadhyaksha', 'उपाध्यक्ष'), ('sachiv', 'सचिव'), ('kosadhyaksha', 'कोषाध्यक्ष'), ('sadasya', 'सदस्य')], default='sadasya', max_length=50),
        ),
    ]
