# Generated by Django 6.0 on 2025-12-13 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_member_is_monitoring_committee_alter_member_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='is_monitoring_committee',
            new_name='is_monitoring_committee_member',
        ),
    ]
