# Generated by Django 6.0 on 2025-12-13 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_is_monitoring_committee_member_is_monitoring_committee_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='role',
            new_name='designation',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone',
        ),
    ]
