# Generated by Django 6.0 on 2025-12-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_role_member_designation_remove_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='office_model',
            name='nishan_chap',
            field=models.ImageField(blank=True, null=True, upload_to='images/nishan_chap/'),
        ),
        migrations.AddField(
            model_name='office_model',
            name='office_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/office_logo/'),
        ),
    ]
