# Generated by Django 6.0 on 2025-12-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_office_model_nishan_chap_office_model_office_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.IntegerField(verbose_name='सि.न.')),
                ('registration_no', models.CharField(max_length=100, verbose_name='दर्ता नम्बर')),
                ('name', models.CharField(max_length=255, verbose_name='आयोजनाको नाम')),
                ('ward_no', models.PositiveIntegerField(verbose_name='वडा नं.')),
                ('location', models.CharField(max_length=255, verbose_name='स्थान')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='विनियोजित बजेट')),
                ('implementation_level', models.CharField(max_length=100, verbose_name='कार्यान्वयन तह')),
                ('implementation_status', models.CharField(max_length=100, verbose_name='कार्यान्वयनको अवस्था')),
                ('status_date', models.DateField(blank=True, null=True, verbose_name='मिति')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
