# Generated by Django 6.0 on 2025-12-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='implementation_level',
            field=models.CharField(blank=True, max_length=100, verbose_name='कार्यान्वयन तह'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='implementation_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='कार्यान्वयनको अवस्था'),
        ),
    ]
