# Generated by Django 6.0 on 2025-12-20 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_plan_implementation_level_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
