# Generated by Django 6.0.1 on 2026-01-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('english_title', models.CharField(max_length=100)),
                ('view_order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['view_order'],
            },
        ),
    ]
