# Generated by Django 6.0.1 on 2026-02-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chalani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chalani_samuha', models.CharField(default='मुख्य समुह', max_length=100)),
                ('chalani_number', models.PositiveIntegerField(editable=False, unique=True)),
                ('chalani_date', models.DateField()),
                ('letter_receiver', models.CharField(max_length=200)),
                ('letter_date', models.DateField()),
                ('subject', models.CharField(max_length=300)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('sender_section', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['chalani_number'],
            },
        ),
        migrations.CreateModel(
            name='Darta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('darta_samuha', models.CharField(default='मुख्य समुह', max_length=100)),
                ('darta_number', models.PositiveIntegerField(editable=False, unique=True)),
                ('darta_date', models.CharField(max_length=20)),
                ('letter_sender', models.CharField(max_length=200)),
                ('sender_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sender_address', models.TextField(blank=True, null=True)),
                ('letter_date', models.CharField(max_length=20)),
                ('ref_number', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=300)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('letter_catagory', models.CharField(max_length=100)),
                ('receiver_section', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['darta_number'],
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('english_title', models.CharField(max_length=100)),
                ('view_order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['view_order'],
            },
        ),
    ]
