# Generated by Django 6.0.1 on 2026-01-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darta_chalani', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chalani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chalani_samuha', models.CharField(max_length=100)),
                ('chalani_number', models.PositiveIntegerField()),
                ('chalani_date', models.DateField()),
                ('letter_receiver', models.CharField(max_length=200)),
                ('letter_date', models.DateField()),
                ('subject', models.CharField(max_length=300)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('sender_section', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['chalani_number'],
            },
        ),
        migrations.CreateModel(
            name='Darta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('darta_samuha', models.CharField(max_length=100)),
                ('darta_number', models.PositiveIntegerField()),
                ('darta_date', models.DateField()),
                ('letter_sender', models.CharField(max_length=200)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_address', models.TextField()),
                ('letter_date', models.DateField()),
                ('ref_number', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=300)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('letter_catagory', models.CharField(max_length=100)),
                ('receiver_section', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['darta_number'],
            },
        ),
    ]
