# Generated by Django 6.0.1 on 2026-01-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darta_chalani', '0002_chalani_darta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chalani',
            name='chalani_samuha',
            field=models.CharField(default='मुख्य समुह', max_length=100),
        ),
        migrations.AlterField(
            model_name='darta',
            name='darta_samuha',
            field=models.CharField(default='मुख्य समुह', max_length=100),
        ),
    ]
