# Generated by Django 6.0.1 on 2026-01-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darta_chalani', '0003_alter_chalani_chalani_samuha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chalani',
            name='chalani_number',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='darta',
            name='darta_number',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='darta',
            name='sender_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='darta',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
