# Generated by Django 6.0.1 on 2026-01-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darta_chalani', '0004_alter_chalani_chalani_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darta',
            name='darta_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='darta',
            name='letter_date',
            field=models.CharField(max_length=20),
        ),
    ]
